language: java

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/04643d955d03eb39e24e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
