language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6

after_success:
  - mvn findbugs:check
  - mvn clean cobertura:cobertura coveralls:cobertura
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/04643d955d03eb39e24e
    on_success: change
