language: java

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/04643d955d03eb39e24e
    on_success: change  # options: [always|never|change] default: always

# check sources against coding conventions
after_script:
- mvn checkstyle:check
